### ISSUE TITLE
Passing destinationpath input does not work

### ISSUE THREAD

**Issue by tim-pankoke** [SamKirkland/plop-templates#12]
Hi!

It looks like the extension does not execute the plop command correctly so that the `destinationpath` input is not bypassed. This is what the extension executes:

![image](https://user-images.githubusercontent.com/2560969/105385774-00f3a180-5c14-11eb-9754-ef584d90736d.png)

As from the [plop docs](https://plopjs.com/documentation/#bypassing-prompts-by-name-) and what I tried in the console there is a `--` missing:

```bash
$ plop "component" -- --destinationPath "/Users/timhoffmann/dev/github/tim-hoffmann/saas-starter-frontend/src/components"
```

As I can see there has been a [change in v1.1.0](https://github.com/SamKirkland/plop-templates/commit/60fe4b2ec1d584a7a77d4a5f083bad732d21402e#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626L114) which removed the extra `--`. 
Looks like that was by accident? 🤔

Thanks in advance
Tim

**Comment by sebastien-lb** [comment]
Could the fix be as simple as this https://github.com/sebastien-lb/plop-templates/pull/1/files ? @tim-hoffmann I found the same thing as you on the plop documentation. 
I will try to build and test the extension with the modification on my fork before submitting a PR here. @SamKirkland would you be ok to merge if it fix the issue? :)

**Comment by tim-pankoke** [comment]
Hi @sebastien-lb, yes your change looks good to me! It should solve the issue.

**Comment by sebastien-lb** [comment]
I tested locally and the destination path is correctly passed to the plop command and not asked anymore by the prompt. PR is here: https://github.com/SamKirkland/plop-templates/pull/13

**Comment by philiiiiiipp** [comment]
Until this the MR is merged, you can somewhat get around it by changing the command to ` --destinationPath` ( in my case I use `location` ) 

<img width="600" alt="Screenshot 2021-07-09 at 12 52 39" src="https://user-images.githubusercontent.com/1035746/125067424-8d0b5f80-e0b4-11eb-8eb9-0a088157dcc7.png">
