### ISSUE TITLE
It does not seem to skip destinationpath prompt for me

### ISSUE THREAD

**Issue by cmarabate** [SamKirkland/plop-templates#14]
It shows me the path of the directory that I right clicked and choose "New File from Template" but I have to copy it and paste it as the answer to the "Template destination path" prompt in order for it to work correctly. Just leaving that prompt blank does not work...
![image](https://user-images.githubusercontent.com/12236062/165382283-d9db10bc-90ea-4e25-a77f-df8f350b245c.png)

Reading the comment in the plopfile.js you provided and the release notes makes it seem like this extension is supposed to skip that prompt and automatically use the **destinationpath** for me.
![image](https://user-images.githubusercontent.com/12236062/165382797-08f8953f-6639-43ce-8679-bd5482ed24fc.png)

Is there something I still need to configure to get that working or is there a bug with the latest release?

**Comment by tomardern** [comment]
I'm having the same issue - the plop documentation (https://plopjs.com/documentation/#bypassing-prompts-by-name) mentions passing in with `--` eg:

`plop "component" -- --destinationpath "/path/user/selected/goes/here"`

The current version of the extension runs (Note missing --)
`plop "component"  --destinationpath "/path/user/selected/goes/here"`

As a solution, set the vscode plop setting "Destination path" to this::
` --destinationpath` (note the space at the start)
![image](https://user-images.githubusercontent.com/1135454/181224005-2420b811-6a58-4244-9035-1be5e56202ca.png)

**Comment by SamKirkland** [comment]
Fixed in V1.2.0
